= VideoPerimeter

http://ec2-3-121-113-183.eu-central-1.compute.amazonaws.com:8080/VideoPerimeter-1.0-SNAPSHOT/

== Description
В рамках данного проекта разрабатывается веб-приложение для продажи услуг и систем видеонаблюдения. Компания «Видеопериметр» входит в группу компаний, занимающихся установкой систем безопасности и видео наблюдения. Зачастую камеры видеонаблюдения – это последняя надежда граждан на справедливость и решения конфликтных или спорных ситуаций.

=== Какую проблему данный проект решает или что нового приносит для пользователей?
Организация позволяет решить клиентские вопросы в сфере:

* Охраны материальных ценностей, имущества;
* Защита от воровства на складах, частных территориях;
* Контроль сотрудников;
* Наблюдения за ходом работ и поддержка трудовой дисциплины.

Т.к. в основной массе установка производится на частных домах и жилых кооперативах решаются следующие проблемы:

* Контроль входных групп и внутренних помещений подъезда;
* Контроль придомовой территории;
* Контроль парковки автомобильного транспорта;
* Контроль детских площадок.

=== Потенциальные пользователи
Основные объекты, с которыми работает организация:

* Кооперативы (жилые дома, гаражи, садовые товарищества);
* Объекты часного бизнеса (магазины, производства, павильоны, торговые центры, базы техники, склады, строительные площадки, офисы и т.д.).


=== Аналогичные приложения

* http://www.xn--b1aafaeq8bcs.xn--90ais/
* https://dvsvideo.by/
* https://videogorod.by/uslugi/

=== Конкурентное преимущество

* Просмотр актуального ассортимента прямо на сайте и возможность выбрать подходящий товар;
* Онлайн-подбор и получения консультации в выборе комплектующих для полностью готовых систем видеонаблюдения;
* Онлайн-запросы на предоставление видеоархива систем, установленых на многоквартирных домах;
